# Generated by Django 3.2 on 2022-03-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
