# Generated by Django 3.2 on 2022-03-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_mail_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail_confirmed',
        ),
    ]
