# Generated by Django 3.2 on 2022-03-16 20:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_mail_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='invitation_Code',
            new_name='invitation_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
