# Generated by Django 3.2 on 2022-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_alter_servicerequest_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card')], max_length=25),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('initiated', 'initiated'), ('paid', 'paid'), ('not required', 'not required')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('in process', 'created'), ('canceled', 'canceled'), ('DONE', 'DONE')], max_length=25),
        ),
    ]
