# Generated by Django 3.2 on 2022-05-26 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0006_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='payment_unique_ident',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_unique_ident_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=125), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('waiting payment', 'waiting payment'), ('in process', 'in process'), ('canceled', 'canceled'), ('done', 'done')], max_length=25),
        ),
    ]
