# Generated by Django 3.2 on 2022-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0008_auto_20220620_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifterycallback',
            name='giftry_order_id',
            field=models.CharField(default='did', max_length=125),
            preserve_default=False,
        ),
    ]
