# Generated by Django 3.2 on 2022-05-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_requests', '0007_auto_20220526_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrderResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opay_response', models.JSONField(default=dict)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_order_responses', to='service_requests.servicerequest')),
            ],
        ),
    ]
