# Generated by Django 3.2 on 2022-06-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorderresponselog',
            name='callback',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='payorderresponselog',
            name='reference',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
