# Generated by Django 3.2 on 2022-04-09 19:54

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to=services.models.upload_banner_image)),
                ('route', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to=services.models.upload_promotion_image)),
                ('route', models.CharField(max_length=200)),
            ],
        ),
    ]
