# Generated by Django 3.2 on 2022-04-14 08:22

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_homebanner_homepromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='image_ar',
            field=models.ImageField(null=True, upload_to=services.models.upload_banner_image),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='image_en',
            field=models.ImageField(null=True, upload_to=services.models.upload_banner_image),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='title_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
