# Generated by Django 3.2 on 2022-04-14 08:37

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_prerequisite_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepromotion',
            name='image_ar',
            field=models.ImageField(null=True, upload_to=services.models.upload_promotion_image),
        ),
        migrations.AddField(
            model_name='homepromotion',
            name='image_en',
            field=models.ImageField(null=True, upload_to=services.models.upload_promotion_image),
        ),
        migrations.AddField(
            model_name='homepromotion',
            name='title_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepromotion',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='name_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image_ar',
            field=models.ImageField(null=True, upload_to=services.models.upload_service_image, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_en',
            field=models.ImageField(null=True, upload_to=services.models.upload_service_image, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
