# Generated by Django 3.2 on 2022-04-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220414_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='integration_rout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
