# Generated by Django 3.2 on 2022-06-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
