# Generated by Django 3.2 on 2022-08-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='homepromotion',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='homebanner',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homepromotion',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
