# Generated by Django 3.2 on 2022-09-05 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0006_staffassignedcustomersrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffassignedcustomersrequests',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
