# Generated by Django 3.2 on 2022-04-20 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_auto_20220420_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestnotificationsettings',
            name='message',
            field=models.CharField(help_text='تم توصيل طلب رقم {{order_id}}', max_length=125),
        ),
        migrations.AlterField(
            model_name='requestnotificationsettings',
            name='new_status',
            field=models.CharField(choices=[('created', 'created'), ('created', 'created'), ('waiting payment', 'waiting payment'), ('in process', 'in process'), ('canceled', 'canceled'), ('done', 'done')], max_length=25),
        ),
        migrations.AlterField(
            model_name='requestnotificationsettings',
            name='previous_status',
            field=models.CharField(choices=[('created', 'created'), ('created', 'created'), ('waiting payment', 'waiting payment'), ('in process', 'in process'), ('canceled', 'canceled'), ('done', 'done')], max_length=25),
        ),
        migrations.CreateModel(
            name='MyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(max_length=50, unique=True, verbose_name='Device ID')),
                ('reg_id', models.CharField(max_length=255, unique=True, verbose_name='Registration ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'abstract': False,
            },
        ),
    ]
