# Generated by Django 3.2 on 2022-05-08 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_auto_20220420_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnotificationsettings',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=notifications.models.upload_icon),
        ),
        migrations.CreateModel(
            name='UserSavedNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.CharField(max_length=125)),
                ('seen', models.BooleanField(default=False)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.requestnotificationsettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
