# Generated by Django 3.2 on 2022-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20220508_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestnotificationsettings',
            name='new_status',
            field=models.CharField(choices=[('created', 'created'), ('waiting payment', 'waiting payment'), ('in process', 'in process'), ('canceled', 'canceled'), ('done', 'done')], max_length=25),
        ),
        migrations.AlterField(
            model_name='requestnotificationsettings',
            name='previous_status',
            field=models.CharField(choices=[('created', 'created'), ('waiting payment', 'waiting payment'), ('in process', 'in process'), ('canceled', 'canceled'), ('done', 'done')], max_length=25),
        ),
    ]
