# Generated by Django 3.2 on 2022-08-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20220526_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyDevice',
        ),
    ]
